import { PollInstance } from '../Types/cosmicLattePollImportList';

export const example_poll_instance: PollInstance = {
  id: 0,
  idCosmicLatte: '',
  uuid: '',
  name: 'Encuesta de Caracterización',
  version: 'evaluationSets:J9KgH2Q6MyaJGFj69-1/31/2025 1:02:46 PM',
  finishedAt: '2025-01-31T13:02:45.915Z',
  components: [
    {
      name: 'academico',
      variables: [
        {
          name: '¿Hace cuanto se graduó como bachiller?',
          position: 5,
          type: 'multipleChoice',
          answer: {
            answer: 'Recién graduado',
            score: 1,
            pollInstanceId: 0,
            pollVariableId: 0,
            student: {
              id: 0,
              uuid: null,
              name: 'David costa',
              email: 'Daviity',
              studentDetail: null,
              cohort: {
                name: 'Cohort 1 (Enero 2023)',
                courseCode: '',
                audit: null,
              },
              audit: null,
            },
            audit: null,
          },
          audit: null,
        },
        {
          name: '¿Cuál es su nivel de formación máximo completado?',
          position: 6,
          type: 'multipleChoice',
          answer: {
            answer: 'Bachillerato',
            score: 1,
            pollInstanceId: 0,
            pollVariableId: 0,
            student: {
              id: 0,
              uuid: null,
              name: 'asd rfgqw',
              email: '.university',
              studentDetail: null,
              cohort: {
                name: 'Cohort 1 (Enero 2023)',
                courseCode: '',
                audit: null,
              },
              audit: null,
            },
            audit: null,
          },
          audit: null,
        },
        {
          name: 'De las siguientes situaciones seleccione aquellas que presentó durante su educación previa. (Puede seleccionar más de una opción):',
          position: 7,
          type: 'multipleChoice',
          answer: {
            answer:
              'Dificultad en adaptación socialDificultades de salud físicaDificultades de salud emocionalDificultad en adaptación a la metodología virtualDificultad en procesos de aprendizaje',
            score: 23,
            pollInstanceId: 0,
            pollVariableId: 0,
            student: {
              id: 0,
              uuid: null,
              name: 'asd rfgqw',
              email: '.university',
              studentDetail: null,
              cohort: {
                name: 'Cohort 1 (Enero 2023)',
                courseCode: '',
                audit: null,
              },
              audit: null,
            },
            audit: null,
          },
          audit: null,
        },
        {
          name: '¿Actualmente se encuentra cursando otra carrera?',
          position: 8,
          type: 'multipleChoice',
          answer: {
            answer: 'Sí',
            score: 4,
            pollInstanceId: 0,
            pollVariableId: 0,
            student: {
              id: 0,
              uuid: null,
              name: 'asd rfgqw',
              email: '.university',
              studentDetail: null,
              cohort: {
                name: 'Cohort 1 (Enero 2023)',
                courseCode: '',
                audit: null,
              },
              audit: null,
            },
            audit: null,
          },
          audit: null,
        },
        {
          name: '¿Ha tenido procesos académicos incompletos previamente?',
          position: 9,
          type: 'multipleChoice',
          answer: {
            answer: 'Sí',
            score: 4,
            pollInstanceId: 0,
            pollVariableId: 0,
            student: {
              id: 0,
              uuid: null,
              name: 'asd rfgqw',
              email: '.university',
              studentDetail: null,
              cohort: {
                name: 'Cohort 1 (Enero 2023)',
                courseCode: '',
                audit: null,
              },
              audit: null,
            },
            audit: null,
          },
          audit: null,
        },
        {
          name: '¿Recibió orientación vocacional para seleccionar su carrera en Jala University?',
          position: 10,
          type: 'multipleChoice',
          answer: {
            answer: 'Sí',
            score: 1,
            pollInstanceId: 0,
            pollVariableId: 0,
            student: {
              id: 0,
              uuid: null,
              name: 'asd rfgqw',
              email: '.university',
              studentDetail: null,
              cohort: {
                name: 'Cohort 1 (Enero 2023)',
                courseCode: '',
                audit: null,
              },
              audit: null,
            },
            audit: null,
          },
          audit: null,
        },
        {
          name: '¿Qué le hizo elegir Jala University? (Puede seleccionar más de una opción).',
          position: 11,
          type: 'multipleChoice',
          answer: {
            answer:
              'Interés personal y gusto por la programación.Buena oportunidad en el campo laboral.Por recomendación de un amigo o familiar.',
            score: 7,
            pollInstanceId: 0,
            pollVariableId: 0,
            student: {
              id: 0,
              uuid: null,
              name: 'asd rfgqw',
              email: '.university',
              studentDetail: null,
              cohort: {
                name: 'Cohort 1 (Enero 2023)',
                courseCode: '',
                audit: null,
              },
              audit: null,
            },
            audit: null,
          },
          audit: null,
        },
        {
          name: '¿Conoce el plan de estudios de su carrera en Jala University?',
          position: 12,
          type: 'multipleChoice',
          answer: {
            answer: 'Sí',
            score: 1,
            pollInstanceId: 0,
            pollVariableId: 0,
            student: {
              id: 0,
              uuid: null,
              name: 'asd rfgqw',
              email: '.university',
              studentDetail: null,
              cohort: {
                name: 'Cohort 1 (Enero 2023)',
                courseCode: '',
                audit: null,
              },
              audit: null,
            },
            audit: null,
          },
          audit: null,
        },
        {
          name: '¿Cuáles son los tres aspectos más importantes que espera de su experiencia universitaria?',
          position: 13,
          type: 'multipleChoice',
          answer: {
            answer:
              'Calidad académicaInfraestructura y recursosOportunidades de investigación',
            score: 3,
            pollInstanceId: 0,
            pollVariableId: 0,
            student: {
              id: 0,
              uuid: null,
              name: 'asd rfgqw',
              email: '.university',
              studentDetail: null,
              cohort: {
                name: 'Cohort 1 (Enero 2023)',
                courseCode: '',
                audit: null,
              },
              audit: null,
            },
            audit: null,
          },
          audit: null,
        },
        {
          name: '¿Tiene acceso a internet estable y de alta velocidad en su hogar?',
          position: 14,
          type: 'multipleChoice',
          answer: {
            answer: 'Sí',
            score: 1,
            pollInstanceId: 0,
            pollVariableId: 0,
            student: {
              id: 0,
              uuid: null,
              name: 'asd rfgqw',
              email: '.university',
              studentDetail: null,
              cohort: {
                name: 'Cohort 1 (Enero 2023)',
                courseCode: '',
                audit: null,
              },
              audit: null,
            },
            audit: null,
          },
          audit: null,
        },
        {
          name: '¿Cuánto tiempo dispone para dedicarle a sus actividades académicas?',
          position: 15,
          type: 'multipleChoice',
          answer: {
            answer: 'Mas de ocho horas diarias',
            score: 4,
            pollInstanceId: 0,
            pollVariableId: 0,
            student: {
              id: 0,
              uuid: null,
              name: 'asd rfgqw',
              email: '.university',
              studentDetail: null,
              cohort: {
                name: 'Cohort 1 (Enero 2023)',
                courseCode: '',
                audit: null,
              },
              audit: null,
            },
            audit: null,
          },
          audit: null,
        },
        {
          name: '¿Cuál de las siguientes características describe mejor el espacio que tiene para estudiar en casa?',
          position: 16,
          type: 'multipleChoice',
          answer: {
            answer: 'No tengo un espacio destinado para estudiar',
            score: 5,
            pollInstanceId: 0,
            pollVariableId: 0,
            student: {
              id: 0,
              uuid: null,
              name: 'asd rfgqw',
              email: '.university',
              studentDetail: null,
              cohort: {
                name: 'Cohort 1 (Enero 2023)',
                courseCode: '',
                audit: null,
              },
              audit: null,
            },
            audit: null,
          },
          audit: null,
        },
        {
          name: '¿Implementa técnicas y/o herramientas de estudio de manera regular?',
          position: 17,
          type: 'multipleChoice',
          answer: {
            answer: 'Sí',
            score: 2,
            pollInstanceId: 0,
            pollVariableId: 0,
            student: {
              id: 0,
              uuid: null,
              name: 'asd rfgqw',
              email: '.university',
              studentDetail: null,
              cohort: {
                name: 'Cohort 1 (Enero 2023)',
                courseCode: '',
                audit: null,
              },
              audit: null,
            },
            audit: null,
          },
          audit: null,
        },
        {
          name: '¿Cómo se siente con los métodos de estudio que utiliza normalmente?',
          position: 19,
          type: 'multipleChoice',
          answer: {
            answer: 'Muy satisfecho',
            score: 1,
            pollInstanceId: 0,
            pollVariableId: 0,
            student: {
              id: 0,
              uuid: null,
              name: 'asd rfgqw',
              email: '.university',
              studentDetail: null,
              cohort: {
                name: 'Cohort 1 (Enero 2023)',
                courseCode: '',
                audit: null,
              },
              audit: null,
            },
            audit: null,
          },
          audit: null,
        },
        {
          name: 'De los siguientes aspectos indique en cuales presenta mayor dificultad. (Puede seleccionar más de una opción).',
          position: 20,
          type: 'multipleChoice',
          answer: {
            answer:
              'Trabajar contenidos matemáticos y numéricosComprender lecturas y producir escritosMemorizar conceptosGestionar su tiempo para aumentar su productividadDificultad para entender la metodología virtual',
            score: 24,
            pollInstanceId: 0,
            pollVariableId: 0,
            student: {
              id: 0,
              uuid: null,
              name: 'asd rfgqw',
              email: '.university',
              studentDetail: null,
              cohort: {
                name: 'Cohort 1 (Enero 2023)',
                courseCode: '',
                audit: null,
              },
              audit: null,
            },
            audit: null,
          },
          audit: null,
        },
      ],
      audit: null,
    },
    {
      name: 'individual',
      variables: [
        {
          name: 'Estado Civil:',
          position: 21,
          type: 'multipleChoice',
          answer: {
            answer: 'Soltero',
            score: 1,
            pollInstanceId: 0,
            pollVariableId: 0,
            student: {
              id: 0,
              uuid: null,
              name: 'asd rfgqw',
              email: '.university',
              studentDetail: null,
              cohort: {
                name: 'Cohort 1 (Enero 2023)',
                courseCode: '',
                audit: null,
              },
              audit: null,
            },
            audit: null,
          },
          audit: null,
        },
        {
          name: 'Indique si pertenece a alguno de los siguientes grupos de poblaciones:',
          position: 22,
          type: 'multipleChoice',
          answer: {
            answer: 'Ninguna de las anteriores',
            score: 4,
            pollInstanceId: 0,
            pollVariableId: 0,
            student: {
              id: 0,
              uuid: null,
              name: 'asd rfgqw',
              email: '.university',
              studentDetail: null,
              cohort: {
                name: 'Cohort 1 (Enero 2023)',
                courseCode: '',
                audit: null,
              },
              audit: null,
            },
            audit: null,
          },
          audit: null,
        },
        {
          name: 'Indique si pertenece a la comunidad LGBTIQ+',
          position: 24,
          type: 'multipleChoice',
          answer: {
            answer: 'No',
            score: 4,
            pollInstanceId: 0,
            pollVariableId: 0,
            student: {
              id: 0,
              uuid: null,
              name: 'asd rfgqw',
              email: '.university',
              studentDetail: null,
              cohort: {
                name: 'Cohort 1 (Enero 2023)',
                courseCode: '',
                audit: null,
              },
              audit: null,
            },
            audit: null,
          },
          audit: null,
        },
        {
          name: 'Ante una dificultad usted normalmente piensa que:',
          position: 25,
          type: 'multipleChoice',
          answer: {
            answer: 'Es un problema que no va a poder resolver',
            score: 4,
            pollInstanceId: 0,
            pollVariableId: 0,
            student: {
              id: 0,
              uuid: null,
              name: 'asd rfgqw',
              email: '.university',
              studentDetail: null,
              cohort: {
                name: 'Cohort 1 (Enero 2023)',
                courseCode: '',
                audit: null,
              },
              audit: null,
            },
            audit: null,
          },
          audit: null,
        },
        {
          name: '¿Cuál de las siguientes características describe mejor la manera en que usted establece y mantiene amistades?',
          position: 26,
          type: 'multipleChoice',
          answer: {
            answer: 'Tímido y/o alejado',
            score: 4,
            pollInstanceId: 0,
            pollVariableId: 0,
            student: {
              id: 0,
              uuid: null,
              name: 'asd rfgqw',
              email: '.university',
              studentDetail: null,
              cohort: {
                name: 'Cohort 1 (Enero 2023)',
                courseCode: '',
                audit: null,
              },
              audit: null,
            },
            audit: null,
          },
          audit: null,
        },
        {
          name: '¿Con cuál de los siguientes enunciados se identifica usted cuando debe hablar en público?',
          position: 27,
          type: 'multipleChoice',
          answer: {
            answer: 'Se pone muy nervioso y siente que no puede hacerlo.',
            score: 5,
            pollInstanceId: 0,
            pollVariableId: 0,
            student: {
              id: 0,
              uuid: null,
              name: 'asd rfgqw',
              email: '.university',
              studentDetail: null,
              cohort: {
                name: 'Cohort 1 (Enero 2023)',
                courseCode: '',
                audit: null,
              },
              audit: null,
            },
            audit: null,
          },
          audit: null,
        },
        {
          name: '¿Considera que es una persona que logra entender y gestionar sus emociones de manera asertiva?',
          position: 28,
          type: 'multipleChoice',
          answer: {
            answer: 'Sí',
            score: 1,
            pollInstanceId: 0,
            pollVariableId: 0,
            student: {
              id: 0,
              uuid: null,
              name: 'asd rfgqw',
              email: '.university',
              studentDetail: null,
              cohort: {
                name: 'Cohort 1 (Enero 2023)',
                courseCode: '',
                audit: null,
              },
              audit: null,
            },
            audit: null,
          },
          audit: null,
        },
        {
          name: '¿Cuáles de los siguientes apoyos ha necesitado durante su vida? (Puede seleccionar más de una opción).',
          position: 29,
          type: 'multipleChoice',
          answer: {
            answer:
              'Apoyos para el aprendizaje (psicopedagogía)Acompañamiento en salud mental (psicología y/o psiquiatría)Terapia ocupacionalMédicos especialistas',
            score: 16,
            pollInstanceId: 0,
            pollVariableId: 0,
            student: {
              id: 0,
              uuid: null,
              name: 'asd rfgqw',
              email: '.university',
              studentDetail: null,
              cohort: {
                name: 'Cohort 1 (Enero 2023)',
                courseCode: '',
                audit: null,
              },
              audit: null,
            },
            audit: null,
          },
          audit: null,
        },
        {
          name: '¿Tienes acceso a servicios de salud?',
          position: 30,
          type: 'multipleChoice',
          answer: {
            answer: 'Sí',
            score: 1,
            pollInstanceId: 0,
            pollVariableId: 0,
            student: {
              id: 0,
              uuid: null,
              name: 'asd rfgqw',
              email: '.university',
              studentDetail: null,
              cohort: {
                name: 'Cohort 1 (Enero 2023)',
                courseCode: '',
                audit: null,
              },
              audit: null,
            },
            audit: null,
          },
          audit: null,
        },
        {
          name: '¿Padece alguna enfermedad crónica o permanente para la que necesite atención especializada?',
          position: 31,
          type: 'multipleChoice',
          answer: {
            answer: 'Sí',
            score: 5,
            pollInstanceId: 0,
            pollVariableId: 0,
            student: {
              id: 0,
              uuid: null,
              name: 'asd rfgqw',
              email: '.university',
              studentDetail: null,
              cohort: {
                name: 'Cohort 1 (Enero 2023)',
                courseCode: '',
                audit: null,
              },
              audit: null,
            },
            audit: null,
          },
          audit: null,
        },
        {
          name: '¿Tomas medicación regularmente?',
          position: 33,
          type: 'multipleChoice',
          answer: {
            answer: 'Sí',
            score: 5,
            pollInstanceId: 0,
            pollVariableId: 0,
            student: {
              id: 0,
              uuid: null,
              name: 'asd rfgqw',
              email: '.university',
              studentDetail: null,
              cohort: {
                name: 'Cohort 1 (Enero 2023)',
                courseCode: '',
                audit: null,
              },
              audit: null,
            },
            audit: null,
          },
          audit: null,
        },
        {
          name: 'Tiene alguna necesidad educativa especial soportada por un diagnóstico: (Asperger, discapacidad motora, trastornos del lenguaje, TDAH etc.)',
          position: 34,
          type: 'multipleChoice',
          answer: {
            answer: 'Sí',
            score: 5,
            pollInstanceId: 0,
            pollVariableId: 0,
            student: {
              id: 0,
              uuid: null,
              name: 'asd rfgqw',
              email: '.university',
              studentDetail: null,
              cohort: {
                name: 'Cohort 1 (Enero 2023)',
                courseCode: '',
                audit: null,
              },
              audit: null,
            },
            audit: null,
          },
          audit: null,
        },
        {
          name: 'Tiene alguna necesidad emocional especial soportada por un diagnóstico: (depresión, ansiedad, trastorno bipolar etc.).',
          position: 36,
          type: 'multipleChoice',
          answer: {
            answer: 'Sí',
            score: 5,
            pollInstanceId: 0,
            pollVariableId: 0,
            student: {
              id: 0,
              uuid: null,
              name: 'asd rfgqw',
              email: '.university',
              studentDetail: null,
              cohort: {
                name: 'Cohort 1 (Enero 2023)',
                courseCode: '',
                audit: null,
              },
              audit: null,
            },
            audit: null,
          },
          audit: null,
        },
        {
          name: '¿Con qué frecuencia realiza actividad física?',
          position: 38,
          type: 'multipleChoice',
          answer: {
            answer: 'Diariamente',
            score: 1,
            pollInstanceId: 0,
            pollVariableId: 0,
            student: {
              id: 0,
              uuid: null,
              name: 'asd rfgqw',
              email: '.university',
              studentDetail: null,
              cohort: {
                name: 'Cohort 1 (Enero 2023)',
                courseCode: '',
                audit: null,
              },
              audit: null,
            },
            audit: null,
          },
          audit: null,
        },
        {
          name: '¿Con qué frecuencia dedica tiempo a sus hobbies o intereses fuera del horario académico?',
          position: 39,
          type: 'multipleChoice',
          answer: {
            answer: 'Diariamente',
            score: 1,
            pollInstanceId: 0,
            pollVariableId: 0,
            student: {
              id: 0,
              uuid: null,
              name: 'asd rfgqw',
              email: '.university',
              studentDetail: null,
              cohort: {
                name: 'Cohort 1 (Enero 2023)',
                courseCode: '',
                audit: null,
              },
              audit: null,
            },
            audit: null,
          },
          audit: null,
        },
      ],
      audit: null,
    },
    {
      name: 'familiar',
      variables: [
        {
          name: 'Al tomar una decisión familiar ¿A usted lo tienen en cuenta?',
          position: 40,
          type: 'multipleChoice',
          answer: {
            answer: 'Siempre',
            score: 1,
            pollInstanceId: 0,
            pollVariableId: 0,
            student: {
              id: 0,
              uuid: null,
              name: 'asd rfgqw',
              email: '.university',
              studentDetail: null,
              cohort: {
                name: 'Cohort 1 (Enero 2023)',
                courseCode: '',
                audit: null,
              },
              audit: null,
            },
            audit: null,
          },
          audit: null,
        },
        {
          name: 'Cuando usted debe tomar decisiones importantes ¿Consulta la opinión de su familia?',
          position: 41,
          type: 'multipleChoice',
          answer: {
            answer: 'Siempre',
            score: 1,
            pollInstanceId: 0,
            pollVariableId: 0,
            student: {
              id: 0,
              uuid: null,
              name: 'asd rfgqw',
              email: '.university',
              studentDetail: null,
              cohort: {
                name: 'Cohort 1 (Enero 2023)',
                courseCode: '',
                audit: null,
              },
              audit: null,
            },
            audit: null,
          },
          audit: null,
        },
        {
          name: '¿Cuál es el nivel de escolaridad de sus padres?',
          position: 42,
          type: 'multipleChoice',
          answer: {
            answer: 'Primaria',
            score: 4,
            pollInstanceId: 0,
            pollVariableId: 0,
            student: {
              id: 0,
              uuid: null,
              name: 'asd rfgqw',
              email: '.university',
              studentDetail: null,
              cohort: {
                name: 'Cohort 1 (Enero 2023)',
                courseCode: '',
                audit: null,
              },
              audit: null,
            },
            audit: null,
          },
          audit: null,
        },
        {
          name: '¿Actualmente en su familia se presentan algunas de las siguientes situaciones? (Puede escoger más de una opción).',
          position: 43,
          type: 'multipleChoice',
          answer: {
            answer: 'Malas relaciones familiares',
            score: 4,
            pollInstanceId: 0,
            pollVariableId: 0,
            student: {
              id: 0,
              uuid: null,
              name: 'asd rfgqw',
              email: '.university',
              studentDetail: null,
              cohort: {
                name: 'Cohort 1 (Enero 2023)',
                courseCode: '',
                audit: null,
              },
              audit: null,
            },
            audit: null,
          },
          audit: null,
        },
        {
          name: 'Los apoyos recibidos por su familia para realizar sus estudios están orientados a (puede seleccionar más de una opción):',
          position: 44,
          type: 'multipleChoice',
          answer: {
            answer: 'Apoyo económico – gastos de sostenimiento',
            score: 2,
            pollInstanceId: 0,
            pollVariableId: 0,
            student: {
              id: 0,
              uuid: null,
              name: 'asd rfgqw',
              email: '.university',
              studentDetail: null,
              cohort: {
                name: 'Cohort 1 (Enero 2023)',
                courseCode: '',
                audit: null,
              },
              audit: null,
            },
            audit: null,
          },
          audit: null,
        },
        {
          name: '¿Tiene hijos?',
          position: 45,
          type: 'multipleChoice',
          answer: {
            answer: 'Sí',
            score: 4,
            pollInstanceId: 0,
            pollVariableId: 0,
            student: {
              id: 0,
              uuid: null,
              name: 'asd rfgqw',
              email: '.university',
              studentDetail: null,
              cohort: {
                name: 'Cohort 1 (Enero 2023)',
                courseCode: '',
                audit: null,
              },
              audit: null,
            },
            audit: null,
          },
          audit: null,
        },
        {
          name: '¿Usted o su pareja se encuentran en estado de embarazo?',
          position: 46,
          type: 'multipleChoice',
          answer: {
            answer: 'Sí',
            score: 4,
            pollInstanceId: 0,
            pollVariableId: 0,
            student: {
              id: 0,
              uuid: null,
              name: 'asd rfgqw',
              email: '.university',
              studentDetail: null,
              cohort: {
                name: 'Cohort 1 (Enero 2023)',
                courseCode: '',
                audit: null,
              },
              audit: null,
            },
            audit: null,
          },
          audit: null,
        },
      ],
      audit: null,
    },
    {
      name: 'socioeconomico',
      variables: [
        {
          name: '¿Es usted el proveedor económico principal en su familia?',
          position: 47,
          type: 'multipleChoice',
          answer: {
            answer: 'Sí',
            score: 4,
            pollInstanceId: 0,
            pollVariableId: 0,
            student: {
              id: 0,
              uuid: null,
              name: 'asd rfgqw',
              email: '.university',
              studentDetail: null,
              cohort: {
                name: 'Cohort 1 (Enero 2023)',
                courseCode: '',
                audit: null,
              },
              audit: null,
            },
            audit: null,
          },
          audit: null,
        },
        {
          name: '¿Se encuentra trabajando actualmente?',
          position: 48,
          type: 'multipleChoice',
          answer: {
            answer: 'Sí',
            score: 4,
            pollInstanceId: 0,
            pollVariableId: 0,
            student: {
              id: 0,
              uuid: null,
              name: 'asd rfgqw',
              email: '.university',
              studentDetail: null,
              cohort: {
                name: 'Cohort 1 (Enero 2023)',
                courseCode: '',
                audit: null,
              },
              audit: null,
            },
            audit: null,
          },
          audit: null,
        },
        {
          name: '¿Cuáles de los siguientes gastos NO está en condiciones de cubrir con recursos propios o familiares? (Puede seleccionar más de una opción).',
          position: 49,
          type: 'multipleChoice',
          answer: {
            answer: 'Computador y otros dispositivos.',
            score: 4,
            pollInstanceId: 0,
            pollVariableId: 0,
            student: {
              id: 0,
              uuid: null,
              name: 'asd rfgqw',
              email: '.university',
              studentDetail: null,
              cohort: {
                name: 'Cohort 1 (Enero 2023)',
                courseCode: '',
                audit: null,
              },
              audit: null,
            },
            audit: null,
          },
          audit: null,
        },
        {
          name: '¿Actualmente usted se encuentra viviendo en una zona?',
          position: 50,
          type: 'multipleChoice',
          answer: {
            answer: 'Urbana',
            score: 1,
            pollInstanceId: 0,
            pollVariableId: 0,
            student: {
              id: 0,
              uuid: null,
              name: 'asd rfgqw',
              email: '.university',
              studentDetail: null,
              cohort: {
                name: 'Cohort 1 (Enero 2023)',
                courseCode: '',
                audit: null,
              },
              audit: null,
            },
            audit: null,
          },
          audit: null,
        },
      ],
      audit: null,
    },
  ],
  audit: null,
};
