on:
  push:
    branches:
      - feature/ERAS-45/ci_cd
  workflow_dispatch:
jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Convert repo name
        id: convert-name
        uses: actions/github-script@v6
        with:
          script: |
            const repoName = context.payload.repository.name;
            const lowerCaseRepoName = repoName.toLowerCase();
            return lowerCaseRepoName;
      - name: Get short commit sha
        id: set-vars
        run: |
          SHORT_SHA=$(git rev-parse --short $GITHUB_SHA)
          echo "SHORT_SHA=${SHORT_SHA}" >> $GITHUB_ENV
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.convert-name.outputs.result }}:${{ steps.get-latest-tag.outputs.tag }}-${{ env.SHORT_SHA }}-prod
